package com.taiji.admin.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.taiji.admin.model.ODict;
import com.taiji.admin.model.ODictExample;

public interface ODictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_dict
     *
     * @mbg.generated
     */
    long countByExample(ODictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_dict
     *
     * @mbg.generated
     */
    int deleteByExample(ODictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_dict
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_dict
     *
     * @mbg.generated
     */
    int insert(ODict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_dict
     *
     * @mbg.generated
     */
    int insertSelective(ODict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_dict
     *
     * @mbg.generated
     */
    List<ODict> selectByExample(ODictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_dict
     *
     * @mbg.generated
     */
    ODict selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_dict
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ODict record, @Param("example") ODictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_dict
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ODict record, @Param("example") ODictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_dict
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ODict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_dict
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ODict record);
}