package com.taiji.admin.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.taiji.admin.model.SOrg;
import com.taiji.admin.model.SOrgExample;

public interface SOrgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_classify
     *
     * @mbg.generated
     */
    long countByExample(SOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_classify
     *
     * @mbg.generated
     */
    int deleteByExample(SOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_classify
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_classify
     *
     * @mbg.generated
     */
    int insert(SOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_classify
     *
     * @mbg.generated
     */
    int insertSelective(SOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_classify
     *
     * @mbg.generated
     */
    List<SOrg> selectByExample(SOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_classify
     *
     * @mbg.generated
     */
    SOrg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_classify
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SOrg record, @Param("example") SOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_classify
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SOrg record, @Param("example") SOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_classify
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_classify
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SOrg record);

    List<SOrg> subOrgs(String pid);
    
    String queryOrgsByName(String name);

	String orgChildren(String id);

	String orgParents(String id);
	
	String orgParent(String id);
	
	SOrg selectByCode(String code);
	
	SOrg selectByName(String name);
	
    int deleteByCode(String code);

	List<Map<String, Object>> nextLevel(String name);
}