package com.taiji.admin.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.taiji.admin.model.SPermission;
import com.taiji.admin.model.SPermissionExample;

public interface SPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_permission
     *
     * @mbg.generated
     */
    long countByExample(SPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_permission
     *
     * @mbg.generated
     */
    int deleteByExample(SPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_permission
     *
     * @mbg.generated
     */
    int insert(SPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_permission
     *
     * @mbg.generated
     */
    int insertSelective(SPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_permission
     *
     * @mbg.generated
     */
    List<SPermission> selectByExample(SPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_permission
     *
     * @mbg.generated
     */
    SPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SPermission record, @Param("example") SPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SPermission record, @Param("example") SPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SPermission record);
    
    List<SPermission> selectByRole(Integer rid);

	List<Map<String, Object>> members();
}