package com.taiji.admin.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.taiji.admin.model.SRole;
import com.taiji.admin.model.SRoleExample;

public interface SRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated
     */
    long countByExample(SRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated
     */
    int deleteByExample(SRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated
     */
    int insert(SRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated
     */
    int insertSelective(SRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated
     */
    List<SRole> selectByExample(SRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated
     */
    SRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SRole record, @Param("example") SRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SRole record, @Param("example") SRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SRole record);

	SRole selectRoleFullMsg(Integer id);

	List<Map<String, Object>> members();

	long checkRole(Integer id);
}