package com.taiji.admin.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.taiji.admin.model.SRolePer;
import com.taiji.admin.model.SRolePerExample;

public interface SRolePerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role_per
     *
     * @mbg.generated
     */
    long countByExample(SRolePerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role_per
     *
     * @mbg.generated
     */
    int deleteByExample(SRolePerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role_per
     *
     * @mbg.generated
     */
    int insert(SRolePer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role_per
     *
     * @mbg.generated
     */
    int insertSelective(SRolePer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role_per
     *
     * @mbg.generated
     */
    List<SRolePer> selectByExample(SRolePerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role_per
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SRolePer record, @Param("example") SRolePerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role_per
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SRolePer record, @Param("example") SRolePerExample example);
}