package com.taiji.admin.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.taiji.admin.model.SUserRole;
import com.taiji.admin.model.SUserRoleExample;

public interface SUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbg.generated
     */
    long countByExample(SUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbg.generated
     */
    int deleteByExample(SUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbg.generated
     */
    int insert(SUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbg.generated
     */
    int insertSelective(SUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbg.generated
     */
    List<SUserRole> selectByExample(SUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SUserRole record, @Param("example") SUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SUserRole record, @Param("example") SUserRoleExample example);
}