package com.taiji.admin.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.taiji.admin.model.TFileRef;
import com.taiji.admin.model.TFileRefExample;

public interface TFileRefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbg.generated
     */
    long countByExample(TFileRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbg.generated
     */
    int deleteByExample(TFileRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbg.generated
     */
    int insert(TFileRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbg.generated
     */
    int insertSelective(TFileRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbg.generated
     */
    List<TFileRef> selectByExample(TFileRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TFileRef record, @Param("example") TFileRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TFileRef record, @Param("example") TFileRefExample example);
}